services:
  _defaults:
    public: true

  multisafepay:
    class: MultisafepayOfficial
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'multisafepayofficial'

  multisafepay.sdk_service:
    class: MultiSafepay\PrestaShop\Services\SdkService

  multisafepay.customer_service:
    class: MultiSafepay\PrestaShop\Services\CustomerService

  multisafepay.issuer_service:
    class: MultiSafepay\PrestaShop\Services\IssuerService
    arguments:
      - "@multisafepay.sdk_service"

  multisafepay.payment_option_service:
    class: MultiSafepay\PrestaShop\Services\PaymentOptionService
    arguments:
      - "@multisafepay"

  multisafepay.shopping_cart_service:
    class: MultiSafepay\PrestaShop\Services\ShoppingCartService
    arguments:
      - "@multisafepay"

  multisafepay.order_service:
    class: MultiSafepay\PrestaShop\Services\OrderService
    arguments:
      - "@multisafepay"
      - "@multisafepay.customer_service"
      - "@multisafepay.shopping_cart_service"
      - "@multisafepay.sdk_service"

  multisafepay.tokenization_service:
    class: MultiSafepay\PrestaShop\Services\TokenizationService
    arguments:
      - "@multisafepay"
      - "@multisafepay.sdk_service"

  multisafepay.refund_service:
    class: MultiSafepay\PrestaShop\Services\RefundService
    arguments:
      - "@multisafepay"
      - "@multisafepay.sdk_service"
      - "@multisafepay.payment_option_service"

  multisafepay.notification_service:
    class: MultiSafepay\PrestaShop\Services\NotificationService
    arguments:
      - "@multisafepay"
      - "@multisafepay.sdk_service"
      - "@multisafepay.payment_option_service"

  multisafepay.system_status_service:
    class: MultiSafepay\PrestaShop\Services\SystemStatusService
    arguments:
      - "@multisafepay"
