name: PHPStan
on:
  pull_request:
    branches:
      - main
jobs:
  php_stan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run docker compose
        run: docker-compose up -d app db
      - name: Sleep for 60 seconds to let PrestaShop installation script finish the process
        run: sleep 60s
        shell: bash
      - name: Install MultiSafepay plugin
        run:  make install
      - name: Run PHPStan PrestaShop 1.7
        run:  make phpstan
