name: PHPStan
on:
  pull_request:
    branches:
      - main
jobs:
  php_stan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run docker compose
        run:  docker-compose up -d
      - name: Install Composer dependencies PrestaShop 1.7
        run:  docker exec -e XDEBUG_MODE=off --workdir /var/www/html/modules/multisafepay prestashop-1.7 composer install
      - name: Run PHPStan PrestaShop 1.7
        run:  docker exec -e XDEBUG_MODE=off --workdir /var/www/html/modules/multisafepay prestashop-1.7 composer run-script phpstan

