name: PHPUnit
on:
  pull_request:
    branches:
      - main
jobs:
  php_stan:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run docker compose
        run:  docker-compose up -d
      - name: Install Composer dependencies PrestaShop 1.7
        run:  docker exec --workdir /var/www/html/modules/multisafepay prestashop-1.7 composer install
      - name: Run PHPUnit PrestaShop 1.7
        run:  docker exec -e XDEBUG_MODE=coverage --workdir /var/www/html/modules/multisafepay prestashop-1.7 php vendor/bin/phpunit --coverage-clover=coverage.xml --testsuite prestashop-unit-tests
      - name: Send coverage.xml to codecov
        run:  bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
